name: flutter_openhab
description: A Flutter app for openHAB
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.2 <4.0.0"#

dependencies:
  adaptive_theme: ^3.7.2
  alphabet_list_view: ^1.2.0
  app_badge_plus: ^1.2.6
  auto_hyphenating_text: ^0.3.1
  auto_size_text: ^3.0.0
  badges: ^3.1.2
  cached_memory_image: ^1.5.0
  cached_network_image: ^3.4.1
  camera: ^0.11.3
  chopper: ^8.5.0
  collection: any
  color_models: ^2.0.0
  color_palette_generator: ^2.0.1
  connectivity_plus: ^7.0.0
  cronet_http: ^1.7.0
  cupertino_http: ^2.4.0
  custom_refresh_indicator: ^4.0.1
  dart_date: ^1.5.3
  device_info_plus: ^12.3.0
  dio: ^5.9.0
  drift: ^2.30.0
  drift_flutter: ^0.2.8
  dropdown_button2: ^2.3.9
  dynamic_color: ^1.8.1
  equatable: ^2.0.7
  expandable_page_view: ^1.2.0
  fetch_client: ^1.2.0
  fl_chart: ^1.1.1
  flex_color_picker: ^3.8.0
  flutter:
    sdk: flutter
  flutter_client_sse:
    git:
      url: https://github.com/santitigaga/flutter_client_sse.git
      ref: feat/retry
  flutter_code_editor: ^0.3.5
  flutter_expandable_fab: ^2.5.2
  flutter_form_builder: ^10.2.0
  flutter_iconpicker: ^4.0.3
  flutter_inappwebview: ^6.1.5
  flutter_local_notifications: ^19.5.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.2.2
  flutter_map_marker_popup_plus: ^7.1.0
  flutter_multi_select_items: ^0.4.3
  flutter_native_splash: ^2.4.7
  flutter_picker: ^2.1.0
  flutter_secure_storage: ^10.0.0
  flutter_settings_ui: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutterlifecyclehooks: ^5.0.0
  form_builder_cupertino_fields: ^0.6.0
  form_builder_extra_fields: ^12.1.0
  form_builder_validators: ^11.2.0
  gap: ^3.0.1
  geekyants_flutter_gauges: ^1.0.4
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  get_it: ^8.3.0
  go_router: ^17.0.1
  google_mlkit_face_detection: ^0.13.1
  hive_ce: ^2.16.0
  hive_ce_flutter: ^2.3.3
  http_parser: ^4.1.2
  in_date_utils: ^1.3.0
  internet_connection_checker_plus: ^2.9.1+2
  intl: any
  intl_utils: ^2.8.13
  jovial_svg: ^1.1.28
  json_annotation: ^4.9.0
  latlong2: ^0.9.1
  logger: ^2.6.2
  modal_bottom_sheet: 3.0.0
  multicast_dns: ^0.3.3
  multiple_stream_builder: ^3.0.2
  omni_datetime_picker: ^2.3.1
  package_info_plus: ^8.3.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  quiver: ^3.2.2
  reorderable_staggered_scroll_view: ^0.0.2
  reorderables: ^0.6.0
  rx_shared_preferences: ^4.0.0
  rxdart: ^0.28.0
  screen_brightness: ^2.1.7
  shimmer: ^3.0.0
  smooth_page_indicator: ^2.0.1
  sprintf: 7.0.0
  stacked: ^3.5.0
  stacked_services: ^1.6.0
  toggle_switch: ^2.3.0
  tuple: ^2.0.2
  url_launcher: ^6.3.2
  uuid: ^4.5.2
  wakelock_plus: ^1.3.2
  weather_icons: ^3.0.0
  weather_pack: ^1.2.0

dev_dependencies:
  build_runner: ^2.10.4
  chopper_generator: ^8.5.0
  drift_dev: ^2.30.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  dart_pubspec_licenses: ^3.0.12
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.11.0
  json_serializable: ^6.11.3
  pubspec_dependency_sorter: ^1.0.5
  translations_cleaner: ^0.0.5

dependency_overrides:
  reorderable_staggered_scroll_view:
    git:
      url: https://github.com/Phoenix-TU/reorderable_staggered_scroll_view.git
      ref: main

flutter:

  assets:
    - res/
    - res/fonts/
    - res/images/

  fonts:
    - family: LineIconsFilled
      fonts:
        - asset: res/fonts/LineIconsFilled.ttf
    - family: LineIcons
      fonts:
        - asset: res/fonts/LineIcons.ttf
    - family: LineIconsLight
      fonts:
        - asset: res/fonts/LineIconsLight.ttf
    - family: LineIconsV5
      fonts:
        - asset: res/fonts/LineIconsV5.ttf
  generate: true
  uses-material-design: true

flutter_intl:
  enabled: true

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: res/images/logo.png
  android: true
  ios: true
  web: false
