name: flutter_openhab
version: 1.0.0+1
publish_to: none
description: A Flutter app for openHAB

environment: 
  sdk: '>=3.2.2 <4.0.0'

dependencies: 
  adaptive_theme: ^3.6.0
  auto_hyphenating_text: ^0.2.0
  auto_size_text: ^3.0.0
  azlistview_plus: ^3.0.0
  babstrap_settings_screen: ^0.1.6
  badges: ^3.1.2
  cached_memory_image: ^1.5.0
  cached_network_image: ^3.3.1
  chopper: ^8.0.0
  color_palette_generator: ^2.0.1
  connectivity_plus: ^6.0.3
  cronet_http: ^1.2.0
  cupertino_http: ^1.4.0
  custom_refresh_indicator: ^3.1.0
  dart_date: ^1.3.2
  device_info_plus: ^10.1.0
  dio: ^5.4.3+1
  drift: ^2.18.0
  dropdown_button2: ^2.3.9
  dynamic_color: ^1.7.0
  equatable: ^2.0.5
  expandable_page_view: ^1.0.17
  fetch_client: ^1.1.1
  fl_chart: ^0.68.0
  flutter_app_badger: ^1.5.0
  flutter_client_sse: ^2.0.1
  flutter_form_builder: ^9.2.1
  flutter_iconpicker: ^3.3.3 # upgrade after wakelock_plus
  flutter_inappwebview: ^6.0.0
  flutter_local_notifications: ^17.1.2
  flutter_multi_select_items: ^0.4.2
  flutter_native_splash: ^2.4.0
  flutter_picker: ^2.1.0
  flutter_secure_storage: ^9.2.1
  flutter_staggered_grid_view: ^0.7.0
  flutterlifecyclehooks: ^4.0.0
  form_builder_cupertino_fields: ^0.2.1
  form_builder_extra_fields: ^10.1.0
  form_builder_validators: ^9.1.0
  gap: ^3.0.1
  geekyants_flutter_gauges: ^1.0.4
  geolocator: ^12.0.0
  get_it: ^7.7.0
  go_router: ^14.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  home_widget: ^0.6.0
  http_parser: ^4.0.2
  in_date_utils: ^1.2.1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  intl_utils: ^2.8.7
  jovial_svg: ^1.1.21
  json_annotation: ^4.9.0
  logger: ^2.3.0
  logging: ^1.2.0
  modal_bottom_sheet: 3.0.0
  multiple_stream_builder: ^3.0.2
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  quiver: ^3.2.1
  rxdart: ^0.27.7
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  sprintf: 7.0.0
  sqlite3_flutter_libs: ^0.5.21
  stacked: ^3.4.2
  stacked_services: ^1.5.0
  streaming_shared_preferences: ^2.0.0
  tuple: ^2.0.2
  url_launcher: ^6.2.6
  wakelock_plus: ^1.2.5
  weather_icons: ^3.0.0
  weather_pack: ^1.1.0
  workmanager: ^0.5.2
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

dev_dependencies: 
  build_runner: ^2.4.10
  build_runner_core: ^7.3.0
  chopper_generator: ^8.0.0
  drift_dev: ^2.18.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  pubspec_dependency_sorter: ^1.0.4
  swagger_dart_code_generator: ^2.15.2
  translations_cleaner: ^0.0.5
  flutter_test: 
    sdk: flutter

dependency_overrides:
  intl: ^0.19.0
  uuid: ">=4.2.1"
  flutter_native_timezone: 
    git: 
      url: https://github.com/iamzeeshanali/flutter_native_timezone.git
      ref: zeeshan-vemp
  swagger_dart_code_generator:
    git:
      url: https://github.com/af-chacon/swagger-dart-code-generator.git
      ref: user/aedis/fix-chopper-8-iterceptor-generation
  flutter_colorpicker:
    git: https://github.com/mchome/flutter_colorpicker.git

flutter: 
  assets: 
    - res/
    - res/fonts/
    - res/images/
  fonts: 
    - family: LineIconsFilled
      fonts: 
        - asset: res/fonts/LineIconsFilled.ttf
    - family: LineIcons
      fonts: 
        - asset: res/fonts/LineIcons.ttf
    - family: LineIconsLight
      fonts: 
        - asset: res/fonts/LineIconsLight.ttf
  generate: true
  uses-material-design: true

flutter_intl: 
  enabled: true
