name: flutter_openhab
description: "A Flutter app for openHAB"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  auto_size_text: ^3.0.0
  badges: ^3.1.2
  cached_network_image: ^3.3.1
  chopper: ^7.1.0+1
  color_palette_generator: ^2.0.1
  connectivity_plus: ^5.0.2
  dart_date: ^1.3.2
  dio: ^5.4.0
  drift: ^2.14.1
  dynamic_color: ^1.6.9
  equatable: ^2.0.5
  fl_chart: ^0.66.0
  flutter_app_badger: ^1.5.0
  flutter_form_builder: ^9.1.1
  flutter_inappwebview: ^6.0.0
  flutter_local_notifications: ^16.3.0
  flutter_multi_select_items: ^0.4.2
  flutter_native_splash: ^2.3.9
  flutter_picker: ^2.1.0
  flutterlifecyclehooks: ^4.0.0
  form_builder_cupertino_fields: ^0.2.1
  form_builder_validators: ^9.1.0
  form_builder_extra_fields: ^10.1.0
  get_it: ^7.6.6
  go_router: ^13.0.1
  home_widget: ^0.4.1
  http_parser: ^4.0.2
  in_date_utils: ^1.2.0+2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  intl_utils: ^2.8.7
  jovial_svg: ^1.1.20
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  logging: ^1.2.0
  modal_bottom_sheet: 3.0.0-pre
  multiple_stream_builder: ^3.0.2
  package_info_plus: ^5.0.1
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  provider: ^6.1.1
  quiver: ^3.2.1
  rxdart: ^0.27.7
  shimmer: ^3.0.0
  sqlite3_flutter_libs: ^0.5.19+1
  stacked: ^3.4.1+1
  stacked_services: ^1.3.0
  streaming_shared_preferences: ^2.0.0
  tuple: ^2.0.2
  url_launcher: ^6.2.3
  workmanager: ^0.5.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  device_info_plus: ^9.1.1
  smooth_page_indicator: ^1.1.0
  expandable_page_view: ^1.0.17
  flutter_secure_storage: ^9.0.0
  flutter_iconpicker: ^3.2.4
  azlistview_plus: ^3.0.0
  dropdown_button2: ^2.3.9
  custom_refresh_indicator: ^3.0.0
  auto_hyphenating_text: ^0.2.0
  flutter_staggered_grid_view: ^0.7.0
  sprintf: 7.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_client_sse: ^2.0.1
  cached_memory_image: ^1.5.0
  babstrap_settings_screen: ^0.1.6
  adaptive_theme: ^3.5.0

dependency_overrides:
  flutter_native_timezone:
    git:
      url: https://github.com/iamzeeshanali/flutter_native_timezone.git
      ref: zeeshan-vemp
  uuid: ^4.2.1

dev_dependencies:
  build_runner: ^2.4.8
  build_runner_core: ^7.2.11
  chopper_generator: ^7.1.0
  drift_dev: ^2.14.1
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  swagger_dart_code_generator: ^2.14.2
  translations_cleaner: ^0.0.5
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - res/
    - res/fonts/
  generate: true
  uses-material-design: true

  fonts:
    - family: LineIconsFilled
      fonts:
        - asset: res/fonts/LineIconsFilled.ttf
    - family: LineIcons
      fonts:
        - asset: res/fonts/LineIcons.ttf
    - family: LineIconsLight
      fonts:
        - asset: res/fonts/LineIconsLight.ttf

flutter_intl:
  enabled: true