name: flutter_openhab
version: 1.0.0+1
publish_to: none
description: A Flutter app for openHAB

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  adaptive_theme: ^3.7.0
  app_badge_plus: ^1.2.3
  auto_hyphenating_text: ^0.3.0
  auto_size_text: ^3.0.0
  alphabet_list_view: ^1.1.6
  badges: ^3.1.2
  cached_memory_image: ^1.5.0
  cached_network_image: ^3.4.1
  camera: ^0.11.1
  camera_android: ^0.10.10+3
  chopper: ^8.1.0
  color_palette_generator: ^2.0.1
  connectivity_plus: ^6.1.4
  collection: any
  cronet_http: ^1.3.4
  cupertino_http: ^2.2.0
  custom_refresh_indicator: ^4.0.1
  dart_date: ^1.5.3
  device_info_plus: ^11.5.0
  dio: ^5.8.0+1
  drift: ^2.27.0
  drift_flutter: ^0.2.4
  dropdown_button2: ^2.3.9
  dynamic_color: ^1.7.0
  equatable: ^2.0.7
  expandable_page_view: ^1.0.17
  fetch_client: ^1.1.4
  fl_chart: ^1.0.0
  flutter_client_sse: ^2.0.3
  flutter_form_builder: ^10.0.1
  flutter_iconpicker: ^4.0.1
  flutter_inappwebview: ^6.1.5
  flutter_local_notifications: ^19.3.0
  flutter_multi_select_items: ^0.4.3
  flutter_native_splash: ^2.4.6 # after update of flutter_iconpicker
  flutter_picker: ^2.1.0
  flutter_secure_storage: ^9.2.4
  flutter_staggered_grid_view: ^0.7.0
  flutterlifecyclehooks: ^5.0.0
  form_builder_cupertino_fields: # ^0.5.0
    git:
      url: https://github.com/flutter-form-builder-ecosystem/form_builder_cupertino_fields.git
  form_builder_extra_fields: ^12.0.0
  form_builder_validators: ^11.2.0
  gap: ^3.0.1
  geekyants_flutter_gauges: ^1.0.4
  geocoding: ^4.0.0
  geolocator: ^14.0.1
  get_it: ^8.0.3
  go_router: ^15.2.4
  google_mlkit_face_detection: ^0.13.1
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  # home_widget: ^0.7.0+1
  http_parser: ^4.1.2
  in_date_utils: ^1.2.3
  internet_connection_checker_plus: ^2.7.2
  intl: any
  intl_utils: ^2.8.10
  jovial_svg: ^1.1.27
  json_annotation: ^4.9.0
  logger: ^2.6.0
  modal_bottom_sheet: 3.0.0
  multiple_stream_builder: ^3.0.2
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  provider: ^6.1.5
  quiver: ^3.2.2
  rxdart: ^0.28.0
  flutter_settings_ui: ^3.0.1
  screen_brightness: ^2.1.4
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  sprintf: 7.0.0
  stacked: ^3.4.4
  stacked_services: ^1.6.0
  rx_shared_preferences: ^4.0.0
  tuple: ^2.0.2
  url_launcher: ^6.3.1
  wakelock_plus: ^1.3.2
  weather_icons: ^3.0.0
  weather_pack: ^1.2.0
  # workmanager: ^0.5.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  multicast_dns: ^0.3.3
  # android_multicast_lock: ^1.0.2
  color_models: ^2.0.0
  flex_color_picker: ^3.7.1
  flutter_map: ^8.1.1
  flutter_map_cache: ^2.0.0+1
  # dio_cache_interceptor_hive_store: ^4.0.0
  http_cache_hive_store: ^5.0.1
  latlong2: ^0.9.1
  flutter_map_marker_popup_plus: ^7.1.0
  flutter_expandable_fab: ^2.5.2
  uuid: ^4.5.1
  omni_datetime_picker: ^2.1.1
  toggle_switch: ^2.3.0
  # cron_form_field: ^0.7.0 extended in project
  flutter_code_editor: ^0.3.3
  reorderable_staggered_scroll_view: ^0.0.2
  reorderables: ^0.6.0

dev_dependencies:
  build_runner: ^2.5.4
  chopper_generator: ^8.1.0
  drift_dev: ^2.27.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_oss_licenses: ^3.0.4
  hive_ce_generator: ^1.9.2
  json_serializable: ^6.9.5
  pubspec_dependency_sorter: ^1.0.5
  swagger_dart_code_generator: ^3.0.3
  translations_cleaner: ^0.0.5
  flutter_test:
    sdk: flutter

dependency_overrides:
  reorderable_staggered_scroll_view:
    git:
      url: https://github.com/Phoenix-TU/reorderable_staggered_scroll_view.git
      ref: main
  flutter_iconpicker:
    path: ../libraries/FlutterIconPicker

flutter:
  assets:
    - res/
    - res/fonts/
    - res/images/
  fonts:
    - family: LineIconsFilled
      fonts:
        - asset: res/fonts/LineIconsFilled.ttf
    - family: LineIcons
      fonts:
        - asset: res/fonts/LineIcons.ttf
    - family: LineIconsLight
      fonts:
        - asset: res/fonts/LineIconsLight.ttf
    - family: LineIconsV5
      fonts:
        - asset: res/fonts/LineIconsV5.ttf
  generate: true
  uses-material-design: true

flutter_intl:
  enabled: true

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: "res/images/logo.png"
  android: true
  ios: true
  web: false

# dart run flutter_native_splash:create

#dart run flutter_launcher_icons