name: flutter_openhab
version: 1.0.0+1
publish_to: none
description: A Flutter app for openHAB

environment: 
  sdk: '>=3.2.2 <4.0.0'

dependencies: 
  adaptive_theme: ^3.6.0
  auto_hyphenating_text: ^0.3.0
  auto_size_text: ^3.0.0
  azlistview_plus: ^3.0.0
  badges: ^3.1.2
  cached_memory_image: ^1.5.0
  cached_network_image: ^3.4.1
  chopper: ^8.0.3
  color_palette_generator: ^2.0.1
  connectivity_plus: ^6.1.1
  cronet_http: ^1.3.2
  cupertino_http: ^2.0.1
  custom_refresh_indicator: ^4.0.1
  dart_date: ^1.4.0
  device_info_plus: ^11.2.0
  dio: ^5.7.0
  drift: ^2.22.1
  dropdown_button2: ^2.3.9
  dynamic_color: ^1.7.0
  equatable: ^2.0.7
  expandable_page_view: ^1.0.17
  fetch_client: ^1.1.2
  fl_chart: ^0.70.0
  flutter_app_badger: ^1.5.0
  flutter_client_sse: ^2.0.3
  flutter_form_builder: ^9.6.0
  flutter_iconpicker: ^4.0.1
  flutter_inappwebview: ^6.1.5
  flutter_local_notifications: ^18.0.1
  flutter_multi_select_items: ^0.4.3
  flutter_native_splash: ^2.4.3
  flutter_picker: ^2.1.0
  flutter_secure_storage: ^9.2.2
  flutter_staggered_grid_view: ^0.7.0
  flutterlifecyclehooks: ^5.0.0
  form_builder_cupertino_fields: ^0.5.0
  form_builder_extra_fields: ^11.1.0
  form_builder_validators: ^11.1.1
  gap: ^3.0.1
  geekyants_flutter_gauges: ^1.0.4
  geolocator: ^13.0.2
  get_it: ^8.0.3
  go_router: ^14.6.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  home_widget: ^0.7.0
  http_parser: ^4.1.1
  in_date_utils: ^1.2.1
  internet_connection_checker_plus: ^2.6.0
  intl: any
  intl_utils: ^2.8.7
  jovial_svg: ^1.1.24
  json_annotation: ^4.9.0
  logger: ^2.5.0
  modal_bottom_sheet: 3.0.0
  multiple_stream_builder: ^3.0.2
  package_info_plus: ^8.1.2
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  provider: ^6.1.2
  quiver: ^3.2.2
  rxdart: ^0.28.0
  flutter_settings_ui: ^3.0.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  sprintf: 7.0.0
  sqlite3_flutter_libs: ^0.5.28
  stacked: ^3.4.4
  stacked_services: ^1.6.0
  streaming_shared_preferences: ^2.0.0
  tuple: ^2.0.2
  url_launcher: ^6.3.1
  wakelock_plus: ^1.2.10
  weather_icons: ^3.0.0
  weather_pack: ^1.1.0
  workmanager: ^0.5.2
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  multicast_dns: ^0.3.2+7
  android_multicast_lock: ^1.0.2

dev_dependencies: 
  build_runner: ^2.4.14
  build_runner_core: ^8.0.0
  chopper_generator: ^8.0.3
  drift_dev: ^2.22.1
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  json_serializable: ^6.9.0 # after upgrade of hive_generator
  pubspec_dependency_sorter: ^1.0.5
  swagger_dart_code_generator: ^3.0.1
  translations_cleaner: ^0.0.5
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - res/
    - res/fonts/
    - res/images/
  fonts: 
    - family: LineIconsFilled
      fonts: 
        - asset: res/fonts/LineIconsFilled.ttf
    - family: LineIcons
      fonts: 
        - asset: res/fonts/LineIcons.ttf
    - family: LineIconsLight
      fonts: 
        - asset: res/fonts/LineIconsLight.ttf
    - family: LineIconsV5
      fonts:
        - asset: res/fonts/LineIconsV5.ttf
  generate: true
  uses-material-design: true

flutter_intl: 
  enabled: true

flutter_native_splash:
    color: "#ffffff"
    color_dark: "#000000"
    image: "res/images/logo.png"
    android: true
    ios: true
    web: false

# dart run flutter_native_splash:create

#dart run flutter_launcher_icons